version: "3.8"

services:

  db:
    image: postgres:14.3
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_postgres_password
      - POSTGRES_DB_FILE=/run/secrets/db_postgres_db
    secrets:
      - db_postgres_user
      - db_postgres_password
      - db_postgres_db
    networks:
      - grid_anotation_tool

  adminer:
    image: adminer
    restart: always
    ports:
      - 7777:8080
    networks:
      - grid_anotation_tool

  backend:
    build: docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend/backend
      - media:/images
    working_dir: /backend/
    entrypoint: /entrypoint.sh
    depends_on:
      - db
    environment:
      - PORT=8000
      - PYTHONPATH=/backend
      - APP_MODULE=backend.main:app
      - PRE_START_PATH=/backend/prestart.sh
      - BACKEND_ACCESS_TOKEN_SECRET_KEY_FILE=/run/secrets/backend_access_token_secret_key
      - BACKEND_DATABASE_URL_FILE=/run/secrets/backend_database_url
      - BACKEND_MEDIA_ROOT=/images
      - BACKEND_CORS_ORIGINS=["http://localhost:9999", "http://127.0.0.1:9999", "http://localhost", "http://127.0.0.1"]
    secrets:
      - backend_access_token_secret_key
      - backend_database_url
    command: /start-reload.sh  # production: /start.sh
    restart: always
    networks:
      - grid_anotation_tool

  frontend:
    build: docker
    ports:
      - "9999:9999"
    volumes:
      - ./frontend:/frontend/frontend
    working_dir: /frontend/
    depends_on:
      - db
      - backend
    environment:
      - PORT=9999
      - PYTHONPATH=/frontend
      - APP_MODULE=frontend.main:app
      - PRE_START_PATH=/frontend/prestart.sh
    command: /start-reload.sh  # production: /start.sh
    restart: always
    networks:
      - grid_anotation_tool

secrets:
  db_postgres_user:
    file: ./docker/secrets/db_postgres_user.txt
  db_postgres_db:
    file: ./docker/secrets/db_postgres_db.txt
  db_postgres_password:
    file: ./docker/secrets/db_postgres_password.txt
  backend_database_url:
    file: ./docker/secrets/backend_database_url.txt
  backend_access_token_secret_key:
    file: ./docker/secrets/backend_access_token_secret_key.txt

volumes:
  # postgres DB data
  pgdata: 
  # uplaoded images
  media:

networks:
  grid_anotation_tool:
    name: grid_anotation_tool