version: "3.8"

services:

  frontend:
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./frontend:/app
    #working_dir: /app
    command: gunicorn frontend.main:app --workers=2 --worker-class uvicorn.workers.UvicornWorker
    #depends_on:
    #  - db
    #environment:
    #  - DATABASE_URL=postgresql://pv_module_extractor:9XWC97uf4fwCN7kp@db/pv_module_extractor
    #deploy:
    #  restart_policy:
    #    condition: on-failure
    networks:
      - grid_anotation_tool

  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   #depends_on:
  #   #  - db
  #   #environment:
  #   #  - DATABASE_URL=postgresql://pv_module_extractor:9XWC97uf4fwCN7kp@db/pv_module_extractor
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - grid_anotation_tool

networks:
  grid_anotation_tool:
    name: grid_anotation_tool